twig:
    file_name_pattern: '*.twig'
    form_theme: ['question/base_theme.html.twig']
    paths:
        '%kernel.project_dir%/emails/css': email_css
        '%kernel.project_dir%/emails/template': email_templates

when@test:
    twig:
        strict_variables: true
